export const theme = {
    colors: {
        black: '#05080d',
        red: '#ee4343',
        green: '#77c746',
        yellow: '#ffbc10',
        orange: '#ed8e07',
        stroke: '#fefefe',
        textPlaceholder: '#fefefe',
        textPrimary: '#fefefe',
        textCaption: '#bfbfbf',
        bluePrimary: '#182640',
        blueSecondary: '#283752',
        orangePrimary: '#ff971c',
        orangeSecondary: '#ffbc10',
        backgroundNavbar: '#0e1726',
        labelOrange: '#ff971c',
        labelGreen: '#54a424',
      },
}