# Generated by Django 4.2.11 on 2024-03-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                ("userId", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("setting", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=24)),
            ],
        ),
    ]
