# Generated by Django 4.2.11 on 2024-04-21 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="totalpreptime",
            managers=[],
        ),
        migrations.AlterField(
            model_name="userauth",
            name="uid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="app.userinfo",
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["uid", "default_home", "default_dest"],
                name="app_locatio_uid_id_0830ba_idx",
            ),
        ),
    ]
