# Generated by Django 4.2.11 on 2024-03-20 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userinfo",
            old_name="setting",
            new_name="alarm_sound",
        ),
    ]
