# Generated by Django 5.0.3 on 2024-04-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['uid', 'default_home', 'default_dest'], name='app_locatio_uid_id_0830ba_idx'),
        ),
    ]
