# Generated by Django 4.2.11 on 2024-04-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_totalpreptime"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="totalpreptime",
            name="id",
        ),
        migrations.AlterField(
            model_name="totalpreptime",
            name="iteration",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
