# Generated by Django 4.2.11 on 2024-04-21 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_totalpreptime_managers_alter_userauth_uid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userauth",
            name="uid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="app.userinfo",
                unique=True,
            ),
        ),
    ]
