# Generated by Django 5.0.3 on 2024-04-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userauth_google_id_alter_userinfo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='alarm_sound',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
