# Generated by Django 4.2.11 on 2024-03-24 14:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_location_prepactivitytime_userauth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='prep_activities',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='event_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
