# Generated by Django 5.0.3 on 2024-04-01 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_location_prepactivitytime_userauth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='sched_destination',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='sched_start',
        ),
        migrations.RemoveField(
            model_name='prepactivitytime',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='prep_activities',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='wake_up_aids',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='PrepActivityTime',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
