# Generated by Django 5.0.3 on 2024-04-02 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_userauth_options_alter_userauth_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauth',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelManagers(
            name='userauth',
            managers=[
            ],
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
