# Generated by Django 4.2.11 on 2024-03-24 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_event_id_schedule_temp_event_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='temp_event_id',
            new_name='event_id',
        ),
    ]
