# Generated by Django 4.2.11 on 2024-04-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_temp_event_id_schedule_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='event_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
