# Generated by Django 5.0.3 on 2024-04-03 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_userauth_user_id_alter_userauth_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userauth',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userauth',
            name='last_name',
        ),
    ]
