# Generated by Django 5.0.3 on 2024-04-03 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_userauth_first_name_remove_userauth_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('alarm_sound', models.CharField(max_length=100)),
                ('sched_reminder', models.BooleanField(default=True)),
                ('departure_time', models.BooleanField(default=True)),
                ('new_friends', models.BooleanField(default=True)),
                ('wake_up_aids_requests', models.BooleanField(default=True)),
                ('phone_number', models.CharField(max_length=24)),
                ('total_prep_time', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='userauth',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.userinfo'),
        ),
    ]
