# Generated by Django 5.0.3 on 2024-04-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_userinfo_alter_userauth_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauth',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
