# Generated by Django 5.0.3 on 2024-04-03 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_userauth_user_id_delete_userinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userauth',
            old_name='user_id',
            new_name='uid',
        ),
    ]
