import { theme } from "@/app/theme"
import { StyleSheet } from "react-native"

export const styles = StyleSheet.create({
  handleIndicatorStyle: {
    backgroundColor: theme.colors.textPlaceholder,
    width: 56,
    height: 6,
    alignSelf: "center",
    borderRadius: 3,
    marginTop: 16,
  },
  handleModalIndicatorStyle: {
    backgroundColor: theme.colors.textPlaceholder,
    width: 56,
    height: 6,
    alignSelf: "center",
    borderRadius: 3,
  },
  handleIndicator: {
    display: "none",
  },
  closeButton: {
    width: 32,
    height: 32,
    backgroundColor: theme.colors.textPlaceholder,
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 16,
    // position: "absolute",
  },
  modalCloseButton: {
    width: 32,
    height: 32,
    backgroundColor: theme.colors.textPlaceholder,
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
    position: "absolute",
    right: 0,
    marginRight: 0,
  },
  backdrop: {
    flex: 1,
    backgroundColor: "#142036",
    position: "absolute",
    top: 0,
    width: "100%",
    height: "100%",
    justifyContent: "flex-end",
  },
  bottomSheet: {
    width: "100%",
    height: "78%",
    backgroundColor: theme.colors.bluePrimary,
    bottom: 0,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
  },
  backgroundStyle: {
    backgroundColor: theme.colors.bluePrimary,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    marginTop: 0,
  },
  modalBackgroundStyle: {
    backgroundColor: "#1B2A47",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
  },
  modalLocationBackgroundStyle: {
    backgroundColor: theme.colors.bluePrimary,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
  },
  sheetStyle: {
    flex: 1,
    backgroundColor: theme.colors.bluePrimary,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
  },
  sheetView: {
    marginTop: 32,
    paddingLeft: 32,
    paddingRight: 32,
  },
  modalSheetView: {
    marginTop: 8,
    paddingLeft: 32,
    paddingRight: 32,
    flexGrow: 1
  },
  sheetItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginTop: 24,
  },
  textHeader: {
    color: theme.colors.textCaption,
    fontFamily: "dm-sans-regular",
    fontSize: 16,
  },
  eventNameInput: {
    marginTop: 16,
    marginBottom: 4,
    fontSize: 20,
    fontFamily: "dm-sans-semibold",
    color: theme.colors.textPrimary,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.textCaption,
  },
  textDisplay: {
    fontFamily: "dm-sans-medium",
    color: theme.colors.textPrimary,
  },
  textDisplayBlur: {
    fontFamily: "dm-sans-medium",
    color: theme.colors.textPlaceholder,
  },
  textTitle: {
    fontFamily: "dm-sans-regular",
    fontSize: 16,
    color: theme.colors.textPrimary,
      
  },
  pressableMenu: {
    flexDirection: "row",
    alignItems: "center",
    height: 40,
    paddingLeft: 36,
  },
  chevronStyle: {
    width: 24,
    height: 24,
    right: 0,
    position: "absolute",
  },
  divLine: {
    height: 1,
    backgroundColor: theme.colors.divLine,
    marginTop: 12,
    justifyContent: "flex-end",
  },
  footer: {
    backgroundColor: theme.colors.bluePrimary,
    bottom: 0,
    height: 124,
    flexDirection: "column",
    paddingTop: 8,
    alignItems: "center",
  },
  modalFooter: {
    backgroundColor: theme.colors.modalBackground,
    bottom: 0,
    height: 124,
    flexDirection: "column",
    paddingTop: 8,
    alignItems: "center",
  },
  cancelButton: {
    padding: 8,
    color: theme.colors.textPrimary,
    fontSize: 16,
    fontFamily: "dm-sans-semibold",
    marginTop: 4,
    textDecorationLine: "underline",
  },
  scrollViewContent: {
    flexGrow: 1,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    backgroundColor: theme.colors.bluePrimary,
    paddingTop: 16,
  },
  header: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 56,
    backgroundColor: theme.colors.bluePrimary,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    zIndex: 1, // Ensure the header is on top of the scroll view
  },
  noteInput: {
    marginTop: 8,
    marginBottom: 48,
    fontSize: 16,
    fontFamily: "dm-sans-regular",
    color: theme.colors.textPrimary,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.textCaption,
    marginLeft: 36,
  },
  searchContainer: {
    marginTop: 16,
    marginBottom: 48,
    fontSize: 16,
    fontFamily: "dm-sans-regular",
    color: theme.colors.textPrimary,
    height: 48,
    paddingVertical: 10,
    paddingHorizontal: 16,
    marginHorizontal: 24,
    backgroundColor: theme.colors.blueSecondary,
    borderWidth: 1,
    borderRadius: 20,
    borderColor: theme.colors.stroke,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  searchContainerFocus: {
    marginTop: 16,
    marginBottom: 48,
    fontSize: 16,
    fontFamily: "dm-sans-regular",
    color: theme.colors.textPrimary,
    height: 48,
    paddingVertical: 10,
    paddingHorizontal: 16,
    marginHorizontal: 24,
    backgroundColor: theme.colors.blueSecondary,
    borderWidth: 1,
    borderRadius: 20,
    borderColor: theme.colors.textPrimary,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  searchInput: {
    fontFamily: "dm-sans-regular",
    color: theme.colors.textPrimary,
    fontSize: 16,
  }
})